services:
#  subsciption:
#    depends_on:
#      - database
#    restart: always
#    build:
#      context: gateway
#    environment:
#      SERVER_PORT: 8080
#      SPRING_DATASOURCE_URL: jdbc:postgresql://database/sub-mng
#    ports:
#      - "8080:8080"
  database:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hashtest-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: { }